services:
  schwab-mcp:
    container_name: schwab-mcp
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - SCHWAB_CLIENT_ID=${SCHWAB_CLIENT_ID}
      - SCHWAB_CLIENT_SECRET=${SCHWAB_CLIENT_SECRET}
      - SCHWAB_REDIRECT_URI=${SCHWAB_REDIRECT_URI:-http://localhost:3000/auth/callback}
      - SESSION_SECRET=${SESSION_SECRET}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3000}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  redis:
    container_name: schwab-mcp-redis
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
