// Generated by Wrangler by running `wrangler types`

interface Env {
  schwab_oauth_kv: KVNamespace
  OAUTH_KV: KVNamespace
  SCHWAB_CLIENT_ID: string
  SCHWAB_CLIENT_SECRET: string
  COOKIE_ENCRYPTION_KEY: string
  HOSTED_DOMAIN: string
  MCP_OBJECT: DurableObjectNamespace<import('./src/index').MyMCP>
}
